### ISSUE TITLE
Support for option to highlight/create non-existing lexemes on Text-to-lexemes

### ISSUE THREAD

**Issue by johnsamuelwrites** [fnielsen/ordia#11]
When I add a text to https://tools.wmflabs.org/ordia/text-to-lexemes, I see the list of all the words in the text. It will be useful to separate these words into two categories: words that have associated lexemes on Wikidata and words without them. For those with no associated lexemes, it will be great to either link it to https://www.wikidata.org/wiki/Special:NewLexeme or https://tools.wmflabs.org/lexeme-forms/ (or any other tool).

**Comment by fnielsen** [comment]
Yes, I thought of that. I will require some extract JavaScript as I do not think that dataTables can handle it.

**Comment by fnielsen** [comment]
A link to the search interface is now made with fd1e1bb88ae9bf241444853295a67051953c366c.

A problem with redirecting to https://www.wikidata.org/wiki/Special:NewLexeme is the WDQS lag.
