### ISSUE TITLE
Ordia should pass ?lemma= to wikidata form when creating a new lexeme after searching

### ISSUE THREAD

**Issue by egils-consulting** [fnielsen/ordia#113]

**Comment by fnielsen** [comment]
I am unsure what you mean 
* This link https://ordia.toolforge.org/search?q=hestehale
* will get you to https://www.wikidata.org/wiki/Special:NewLexeme?lemma=hestehale which has the lemma
Do you have an example where it does not work?

**Comment by egils-consulting** [comment]
No, we can close this as I meant something else.
