### ISSUE TITLE
Add false friend to sense

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/ordia#138]
For instance https://www.wikidata.org/wiki/Lexeme:L40926#S1

**Comment by dpriskorn** [comment]
I like this idea. But isn't the other language Swedish in this case missing in this statement?
![image](https://user-images.githubusercontent.com/68460690/177375446-f43908e3-3856-47fc-bedd-d75420d18465.png)

**Comment by fnielsen** [comment]
Perhaps. I am not familar with false friends between Norwegian and Swedish

**Comment by fnielsen** [comment]
https://ordia.toolforge.org/L40926-S1

**Comment by dpriskorn** [comment]
> Perhaps. I am not familar with false friends between Norwegian and Swedish

What I tried to say was that I'm missing a qualifier stating the other language. 

Now it just says danish rar has a false friend in another language but we don't store which in the graph. In this case language->Swedish is missing.

**Comment by dpriskorn** [comment]
None of these seems to fit though.

**Comment by fnielsen** [comment]
I do not understand. L40926-S1 is Danish an link to L471161-S1 which is Bokmål, so the language of both source and target is available.

**Comment by dpriskorn** [comment]
> I do not understand. L40926-S1 is Danish an link to L471161-S1 which is Bokmål, so the language of both source and target is available.

Okay so this is more a UI deficit. The language of the linked thing is not shown.

**Comment by fnielsen** [comment]
```
    ?value_statement ps:P5976 ?value_ .
    ?value_ ^ontolex:sense / wikibase:lemma ?valueLabel_ 
    BIND(CONCAT(?valueLabel_, " (", LANG(?valueLabel_), ")") AS ?valueLabel)
```
