### ISSUE TITLE
Add a toponym map

### ISSUE THREAD

**Issue by belett** [fnielsen/ordia#185]
Hi,

Would it be possible to add a toponym map on language pages (https://ordia.toolforge.org/language/QXXX). Same query as the _Demonym map_ but with P5137 instead of P6271.

Cheers

**Comment by fnielsen** [comment]
@belett Synia currently has a map: https://synia.toolforge.org/#language/Q150/location

**Comment by dpriskorn** [comment]
I suggest we close as won't fix.
