### ISSUE TITLE
Support for other languages in Text-to-lexemes

### ISSUE THREAD

**Issue by johnsamuelwrites** [fnielsen/ordia#20]
Currently https://tools.wmflabs.org/ordia/text-to-lexemes supports seven languages. Is it possible to include other languages? Or are you supporting the languages based on the number of lexemes in a language. So, the seven already chosen languages are the ones with the highest number of lexemes.

**Comment by fnielsen** [comment]
@johnsamuelwrites It is possible to support other languages. If there are any language you specifically want I can add them, otherwise I will need to make a bit more work to include languages generally.

**Comment by fnielsen** [comment]
See also #9

**Comment by johnsamuelwrites** [comment]
Please check PR https://github.com/fnielsen/ordia/pull/22. I have added support to three languages.

**Comment by fnielsen** [comment]
It now runs https://tools.wmflabs.org/ordia/text-to-lexemes

@johnsamuelwrites I wonder if you could check up on whether it works? I am not sure the word tokenization works for Hindi and Malayalam? - Or maybe it is because there are few words in the respective languages. The tokenization is fairly simple at the moment.

**Comment by johnsamuelwrites** [comment]
Thanks @fnielsen. You're right. I will also take a look.

**Comment by fnielsen** [comment]
The word tokenization is just a regular expression: https://github.com/fnielsen/ordia/blob/master/ordia/text.py#L8 Is Devanagari diacritics might be an issue?

**Comment by fnielsen** [comment]
There is apparently some part of the Hindi Unicode that is not by default recognized as a word character
```python
>>> [unicodedata.category(c) for c in "'काशीपुर भारत"]
['Po', 'Lo', 'Mc', 'Lo', 'Mc', 'Lo', 'Mn', 'Lo', 'Zs', 'Lo', 'Mc', 'Lo', 'Lo']
```

**Comment by fnielsen** [comment]
I wonder why you didn't type in the form of രണ്ട് at https://www.wikidata.org/wiki/Lexeme:L2389? The matching of text-to-lexemes happens with the forms.

**Comment by fnielsen** [comment]
It might work now: http://127.0.0.1:5000/text-to-lexemes?text-language=ml&text=%E0%B4%AA%E0%B5%82%E0%B4%A4%E0%B4%95%E0%B5%8D%E0%B4%95%E0%B5%81%E0%B4%9F%E0%B5%8D%E0%B4%9F%E0%B5%BB%20%20%E0%B4%AA%E0%B5%82%E0%B4%A4%E0%B4%95%E0%B5%8D%E0%B4%95%E0%B5%81%E0%B4%9F%E0%B5%8D%E0%B4%9F%E0%B5%BB

**Comment by johnsamuelwrites** [comment]
I checked, it's tokenizing correctly. Thanks. I will add the forms.

**Comment by BodhisattwaMandal** [comment]
For Bengali, #48

**Comment by fnielsen** [comment]
With the PR #254 from @nikkiwd there are now a large number of languages supported
