### ISSUE TITLE
Add Punjabi (pa) to Ordia

### ISSUE THREAD

**Issue by satdeepgill** [fnielsen/ordia#64]
Hey,

Can you please add language code: pa to this tool? Let me know if you need anything.

**Comment by fnielsen** [comment]
This is now enabled https://tools.wmflabs.org/ordia/text-to-lexemes 

Maybe you could give feedback on whether the word tokenization is ok?

**Comment by fnielsen** [comment]
I hope that the tokenization was ok. I am closing this issue. You might want to reopen it if the tokenization is not good (enough).
