### ISSUE TITLE
In language aspect, list of longest words and phrases is missing some of the longest existing lexemes

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/ordia#76]
e.g. in
https://tools.wmflabs.org/ordia/language/Q9260 ,
it currently lists only two entries (with 5 and 6 characters), when several others with more characters exist (e.g. https://tools.wmflabs.org/ordia/L220599 )

**Comment by fnielsen** [comment]
That seems to be because only forms are counted. I suppose lemma's could be counted too, - if they are actual words. I see you have entered at least https://www.wikidata.org/wiki/Lexeme:L226834 Would you be able to enter the form?

**Comment by Daniel-Mietchen** [comment]
Not sure yet how to enter this, but the forms would be 
нав (positive) / навтар (comparative) / навтарин (superlative).

**Comment by Daniel-Mietchen** [comment]
Ha, it was easier than expected - just had newer edited adjective forms without the [lexeme forms](https://tools.wmflabs.org/lexeme-forms/). Works fine now.

Leaving the ticket open because I think including the lemmas would make sense in most cases, but I do not know right now how best to filter for the odd cases.

**Comment by fnielsen** [comment]
That particular lexeme now shows up: https://tools.wmflabs.org/ordia/language/Q9260

**Comment by Daniel-Mietchen** [comment]
Yes, works fine now. Thought a bit more about including the lemmas and now think it's probably better to stick with the current setting of only considering forms.
