### ISSUE TITLE
Map of demonyms

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/ordia#83]

**Comment by fnielsen** [comment]
Running, e.g., at https://tools.wmflabs.org/ordia/language/Q9035

**Comment by ArloJamesBarnes** [comment]
Hm, the example just displays the Wikidata logo in the relevant section for your linked example, with a little box in the lower left corner linking to the WDQS homepage.

**Comment by fnielsen** [comment]
@ArloJamesBarnes. Thanks for your report. In my browser it displays ok for Danish https://ordia.toolforge.org/language/Q9035 and for Russian: https://ordia.toolforge.org/language/Q7737

Perhaps it was a temporary problem with the Wikidata Query Service where the visualization comes from?

**Comment by ArloJamesBarnes** [comment]
No, it persists. But I must admit I'm stumped as to the cause. Firefox' network events inspector pane gives nice green HTTP 200 markers to every resource (with the trivial exception of https://ordia.toolforge.org/images/sort_both.png). Chromium says something about HSTS in the frame embed, but loads the frame just fine by itself:
![image](https://user-images.githubusercontent.com/634501/145952771-b5a3ca92-1d4e-44a4-a6f5-4091faf36743.png)

**Comment by ArloJamesBarnes** [comment]
https://query.wikidata.org/embed.html#%23defaultView%3AMap%0ASELECT%20%3Flexeme%20%3Flemma%20%3Flocation%20%3Fgeo%20%7B%0A%20%20%3Flexeme%20dct%3Alanguage%20wd%3AQ35757%20%3B%0A%20%20%20%20%20%20%20%20%20%20wikibase%3Alemma%20%3Flemma%20%3B%0A%20%20%20%20%20%20%20%20%20%20ontolex%3Asense%20%2F%20wdt%3AP6271%20%3Flocation%20.%0A%20%20%3Flocation%20wdt%3AP625%20%3Fgeo%20.%0A%7D now working in Firefox also, just not when iframed
