### ISSUE TITLE
Lexeme forms do not display any more

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/ordia#96]
e.g. in https://tools.wmflabs.org/ordia/search?language=en&q=foobar , I would expect 
links to things like
https://tools.wmflabs.org/lexeme-forms/template/english-noun?form_representation=foobar 
but these are not there any more.

**Comment by swedebugia** [comment]
I can confirm this. Thanks for the patch Daniel! :)
https://lexeme-forms.toolforge.org/ is the new URL

**Comment by fnielsen** [comment]
This is now fixed with @Daniel-Mietchen PR #97. Thanks for the PR and issue.
